package com.jsh.erp.datasource.entities;

import java.util.ArrayList;
import java.util.List;

/**
 * @Date: 11:03 2020/2/21
 * @Author: ChenShiGen
 * @Description:
 */
public class CustomergroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    protected List<CustomergroupExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public CustomergroupExample() {
        oredCriteria = new ArrayList<CustomergroupExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public List<CustomergroupExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public void or(CustomergroupExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public CustomergroupExample.Criteria or() {
        CustomergroupExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public CustomergroupExample.Criteria createCriteria() {
        CustomergroupExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    protected CustomergroupExample.Criteria createCriteriaInternal() {
        CustomergroupExample.Criteria criteria = new CustomergroupExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<CustomergroupExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<CustomergroupExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<CustomergroupExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<CustomergroupExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new CustomergroupExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new CustomergroupExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new CustomergroupExample.Criterion(condition, value1, value2));
        }

        public CustomergroupExample.Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeEqualTo(String value) {
            addCriterion("Type =", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeNotEqualTo(String value) {
            addCriterion("Type <>", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeGreaterThan(String value) {
            addCriterion("Type >", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Type >=", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeLessThan(String value) {
            addCriterion("Type <", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("Type <=", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeLike(String value) {
            addCriterion("Type like", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeNotLike(String value) {
            addCriterion("Type not like", value, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeIn(List<String> values) {
            addCriterion("Type in", values, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeNotIn(List<String> values) {
            addCriterion("Type not in", values, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeBetween(String value1, String value2) {
            addCriterion("Type between", value1, value2, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("Type not between", value1, value2, "type");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdIn(List<Long> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagIsNull() {
            addCriterion("delete_Flag is null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_Flag is not null");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("delete_Flag =", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("delete_Flag <>", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("delete_Flag >", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("delete_Flag >=", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagLessThan(String value) {
            addCriterion("delete_Flag <", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("delete_Flag <=", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagLike(String value) {
            addCriterion("delete_Flag like", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagNotLike(String value) {
            addCriterion("delete_Flag not like", value, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("delete_Flag in", values, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("delete_Flag not in", values, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("delete_Flag between", value1, value2, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }

        public CustomergroupExample.Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("delete_Flag not between", value1, value2, "deleteFlag");
            return (CustomergroupExample.Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jsh_paytype
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends CustomergroupExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
