package com.jsh.erp.datasource.entities;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * @Date: 9:59 2020/2/24
 * @Author: ChenShiGen
 * @Description:
 */
public class RoyaltyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    protected List<RoyaltyExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public RoyaltyExample() {
        oredCriteria = new ArrayList<RoyaltyExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public List<RoyaltyExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public void or(RoyaltyExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public RoyaltyExample.Criteria or() {
        RoyaltyExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public RoyaltyExample.Criteria createCriteria() {
        RoyaltyExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    protected RoyaltyExample.Criteria createCriteriaInternal() {
        RoyaltyExample.Criteria criteria = new RoyaltyExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jsh_saleName
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends RoyaltyExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jsh_saleName
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<RoyaltyExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<RoyaltyExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<RoyaltyExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<RoyaltyExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new RoyaltyExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new RoyaltyExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new RoyaltyExample.Criterion(condition, value1, value2));
        }

        //Id
        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (RoyaltyExample.Criteria) this;
        }

        //saleId
        public Criteria andSaleIdIsNull() {
            addCriterion("saleId is null");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andSaleIdIsNotNull() {
            addCriterion("saleId is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andSaleIdEqualTo(Long value) {
            addCriterion("saleId =", value, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andSaleIdNotEqualTo(Long value) {
            addCriterion("saleId <>", value, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andSaleIdGreaterThan(Long value) {
            addCriterion("saleId >", value, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("saleId >=", value, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdLessThan(Long value) {
            addCriterion("saleId <", value, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdLessThanOrEqualTo(Long value) {
            addCriterion("saleId <=", value, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdIn(List<Long> values) {
            addCriterion("saleId in", values, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdNotIn(List<Long> values) {
            addCriterion("saleId not in", values, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdBetween(Long value1, Long value2) {
            addCriterion("saleId between", value1, value2, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleIdNotBetween(Long value1, Long value2) {
            addCriterion("saleId not between", value1, value2, "saleId");
            return (RoyaltyExample.Criteria) this;
        }

        //saleName
        public RoyaltyExample.Criteria andSaleNameIsNull() {
            addCriterion("saleName is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameIsNotNull() {
            addCriterion("saleName is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameEqualTo(String value) {
            addCriterion("saleName =", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameNotEqualTo(String value) {
            addCriterion("saleName <>", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameGreaterThan(String value) {
            addCriterion("saleName >", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameGreaterThanOrEqualTo(String value) {
            addCriterion("saleName >=", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameLessThan(String value) {
            addCriterion("saleName <", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameLessThanOrEqualTo(String value) {
            addCriterion("saleName <=", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameLike(String value) {
            addCriterion("saleName like", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameNotLike(String value) {
            addCriterion("saleName not like", value, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameIn(List<String> values) {
            addCriterion("saleName in", values, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameNotIn(List<String> values) {
            addCriterion("saleName not in", values, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameBetween(String value1, String value2) {
            addCriterion("saleName between", value1, value2, "saleName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andSaleNameNotBetween(String value1, String value2) {
            addCriterion("saleName not between", value1, value2, "saleName");
            return (RoyaltyExample.Criteria) this;
        }


        //wholesaleRoyalty
        public RoyaltyExample.Criteria andWholesaleRoyaltyIsNull() {
            addCriterion("wholesaleRoyalty is null");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyIsNotNull() {
            addCriterion("wholesaleRoyalty is not null");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyEqualTo(BigDecimal value) {
            addCriterion("wholesaleRoyalty =", value, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyNotEqualTo(BigDecimal value) {
            addCriterion("wholesaleRoyalty <>", value, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyGreaterThan(BigDecimal value) {
            addCriterion("wholesaleRoyalty >", value, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public Criteria andWholesaleRoyaltyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wholesaleRoyalty >=", value, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyLessThan(BigDecimal value) {
            addCriterion("wholesaleRoyalty <", value, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wholesaleRoyalty <=", value, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyIn(List<BigDecimal> values) {
            addCriterion("wholesaleRoyalty in", values, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyNotIn(List<BigDecimal> values) {
            addCriterion("wholesaleRoyalty not in", values, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wholesaleRoyalty between", value1, value2, "wholesaleRoyalty");
            return (Criteria) this;
        }

        public RoyaltyExample.Criteria andWholesaleRoyaltyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wholesaleRoyalty not between", value1, value2, "wholesaleRoyalty");
            return (Criteria) this;
        }


        //retailRoyalty
        public RoyaltyExample.Criteria andRetailRoyaltyIsNull() {
            addCriterion("retailRoyalty is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyIsNotNull() {
            addCriterion("retailRoyalty is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyEqualTo(BigDecimal value) {
            addCriterion("retailRoyalty =", value, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyNotEqualTo(BigDecimal value) {
            addCriterion("retailRoyalty <>", value, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyGreaterThan(BigDecimal value) {
            addCriterion("retailRoyalty >", value, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("retailRoyalty >=", value, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyLessThan(BigDecimal value) {
            addCriterion("retailRoyalty <", value, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("retailRoyalty <=", value, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyIn(List<BigDecimal> values) {
            addCriterion("retailRoyalty in", values, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyNotIn(List<BigDecimal> values) {
            addCriterion("retailRoyalty not in", values, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retailRoyalty between", value1, value2, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andRetailRoyaltyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retailRoyalty not between", value1, value2, "retailRoyalty");
            return (RoyaltyExample.Criteria) this;
        }


        //allRoyalty
        public RoyaltyExample.Criteria andAllRoyaltyIsNull() {
            addCriterion("allRoyalty is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyIsNotNull() {
            addCriterion("allRoyalty is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyEqualTo(BigDecimal value) {
            addCriterion("allRoyalty =", value, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyNotEqualTo(BigDecimal value) {
            addCriterion("allRoyalty <>", value, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyGreaterThan(BigDecimal value) {
            addCriterion("allRoyalty >", value, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("allRoyalty >=", value, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyLessThan(BigDecimal value) {
            addCriterion("allRoyalty <", value, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("allRoyalty <=", value, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyIn(List<BigDecimal> values) {
            addCriterion("allRoyalty in", values, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyNotIn(List<BigDecimal> values) {
            addCriterion("allRoyalty not in", values, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("allRoyalty between", value1, value2, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAllRoyaltyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("allRoyalty not between", value1, value2, "allRoyalty");
            return (RoyaltyExample.Criteria) this;
        }


        //monthTime
        public RoyaltyExample.Criteria andMonthTimeIsNull() {
            addCriterion("monthTime is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeIsNotNull() {
            addCriterion("monthTime is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeEqualTo(String value) {
            addCriterion("monthTime =", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeNotEqualTo(String value) {
            addCriterion("monthTime <>", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeGreaterThan(String value) {
            addCriterion("monthTime >", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeGreaterThanOrEqualTo(String value) {
            addCriterion("monthTime >=", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeLessThan(String value) {
            addCriterion("monthTime <", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeLessThanOrEqualTo(String value) {
            addCriterion("monthTime <=", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeLike(String value) {
            addCriterion("monthTime like", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeNotLike(String value) {
            addCriterion("monthTime not like", value, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeIn(List<String> values) {
            addCriterion("monthTime in", values, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeNotIn(List<String> values) {
            addCriterion("monthTime not in", values, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeBetween(String value1, String value2) {
            addCriterion("monthTime between", value1, value2, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andMonthTimeNotBetween(String value1, String value2) {
            addCriterion("monthTime not between", value1, value2, "monthTime");
            return (RoyaltyExample.Criteria) this;
        }


        //status
        public RoyaltyExample.Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (RoyaltyExample.Criteria) this;
        }


        //accountId
        public Criteria andAccountIdIsNull() {
            addCriterion("accountId is null");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("accountId is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Long value) {
            addCriterion("accountId =", value, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Long value) {
            addCriterion("accountId <>", value, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Long value) {
            addCriterion("accountId >", value, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdGreaterThanOrEqualTo(Long value) {
            addCriterion("accountId >=", value, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdLessThan(Long value) {
            addCriterion("accountId <", value, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdLessThanOrEqualTo(Long value) {
            addCriterion("accountId <=", value, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdIn(List<Long> values) {
            addCriterion("accountId in", values, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdNotIn(List<Long> values) {
            addCriterion("accountId not in", values, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdBetween(Long value1, Long value2) {
            addCriterion("accountId between", value1, value2, "accountId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountIdNotBetween(Long value1, Long value2) {
            addCriterion("accountId not between", value1, value2, "accountId");
            return (RoyaltyExample.Criteria) this;
        }


        //accountName
        public RoyaltyExample.Criteria andAccountNameIsNull() {
            addCriterion("accountName is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameIsNotNull() {
            addCriterion("accountName is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameEqualTo(String value) {
            addCriterion("accountName =", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameNotEqualTo(String value) {
            addCriterion("accountName <>", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameGreaterThan(String value) {
            addCriterion("accountName >", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("accountName >=", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameLessThan(String value) {
            addCriterion("accountName <", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameLessThanOrEqualTo(String value) {
            addCriterion("accountName <=", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameLike(String value) {
            addCriterion("accountName like", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameNotLike(String value) {
            addCriterion("accountName not like", value, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameIn(List<String> values) {
            addCriterion("accountName in", values, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameNotIn(List<String> values) {
            addCriterion("accountName not in", values, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameBetween(String value1, String value2) {
            addCriterion("accountName between", value1, value2, "accountName");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andAccountNameNotBetween(String value1, String value2) {
            addCriterion("accountName not between", value1, value2, "accountName");
            return (RoyaltyExample.Criteria) this;
        }


        //tenantId
        public RoyaltyExample.Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdIn(List<Long> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (RoyaltyExample.Criteria) this;
        }



        //deleteFlag
        public RoyaltyExample.Criteria andDeleteFlagIsNull() {
            addCriterion("delete_Flag is null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_Flag is not null");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("delete_Flag =", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("delete_Flag <>", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("delete_Flag >", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("delete_Flag >=", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagLessThan(String value) {
            addCriterion("delete_Flag <", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("delete_Flag <=", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagLike(String value) {
            addCriterion("delete_Flag like", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagNotLike(String value) {
            addCriterion("delete_Flag not like", value, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("delete_Flag in", values, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("delete_Flag not in", values, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("delete_Flag between", value1, value2, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }

        public RoyaltyExample.Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("delete_Flag not between", value1, value2, "deleteFlag");
            return (RoyaltyExample.Criteria) this;
        }



    }

}
