package com.jsh.erp.datasource.mappers;

import com.jsh.erp.datasource.entities.Customergroup;
import com.jsh.erp.datasource.entities.CustomergroupExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @Date: 11:40 2020/2/21
 * @Author: ChenShiGen
 * @Description:
 */
public interface CustomergroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int countByExample(CustomergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int deleteByExample(CustomergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int insert(Customergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int insertSelective(Customergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    List<Customergroup> selectByExample(CustomergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    Customergroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Customergroup record, @Param("example") CustomergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Customergroup record, @Param("example") CustomergroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Customergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_Customergroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Customergroup record);
}
