package com.jsh.erp.datasource.mappers;

import com.jsh.erp.datasource.entities.Paytype;
import com.jsh.erp.datasource.entities.PaytypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @Date: 18:30 2020/2/15
 * @Author: ChenShiGen
 * @Description:
 */
public interface PaytypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int countByExample(PaytypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int deleteByExample(PaytypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int insert(Paytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int insertSelective(Paytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    List<Paytype> selectByExample(PaytypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    Paytype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Paytype record, @Param("example") PaytypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Paytype record, @Param("example") PaytypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Paytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_paytype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Paytype record);
}
